### ISSUE TITLE
community-rust-plugin-0.2.2-sources.jar   not loading in sonar 10.3 version and sonar service is shutting down

### ISSUE THREAD

**Issue by rajeshdaddanala** [C4tWithShell/community-rust#84]
received following error 

Caused by: java.lang.NullPointerException: Plugin key is missing from manifest

**Comment by elegoff** [comment]
Hello Rajesh

It looks like you copied the wrong jar in the plugins folder : 
The "community-rust-plugin-0.2.2-sources.jar" should not be used except for getting a backup copy of the plugin **source** code 

Only the other jar file "community-rust-plugin-0.2.2.jar" contains the plugins binary and that one only should be copied in the plugins folder of your sonarqube installation. (i.e you must remove the "community-rust-plugin-0.2.2**-sources**.jar"  )

Let me know if that helps

**Comment by elegoff** [comment]
I locally use "clean install" rather than "clean package" if that helps
