### ISSUE TITLE
There are no verification rules for the Rust language yet

### ISSUE THREAD

**Issue by shanhm1991** [C4tWithShell/community-rust#88]
![image](https://github.com/elegoff/sonar-rust/assets/12453756/3c849a08-b41d-4610-a6cc-a7e3e6f4723e)

is there some additional verification rules for rust

**Comment by elegoff** [comment]
You are correct that there are no addtional verification rules for Rust.
The plugin is limited to reporting Clippy rules via importing external reports

In other words, without importing a Clippy report , SonarQube won't detect any issue

It would be technically possible to add rules in the future but : 
- Are they any Rust rules that are not yet already detected by Clippy ?
- Mimicking Clippy lints to embed them in the plugin (to avoid importing Clippy report) would work but would need to be provided as PR in the project as I am basically a single developer with no bandwith anymore to maintain

Thanks for your understanding
